source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XWKit_Example', :exclusive => true do
  pod 'XWKit', :path => '../'
end

target 'XWKit_Tests', :exclusive => true do
#  pod 'XWKit', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
