use_frameworks!

target 'XWKit_Example' do
  pod 'XWKit', :path => '../'

  target 'XWKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
